version: '3'
networks:
  my-network:
    driver: bridge

services:
  mysql-service:
    environment:
      - MYSQL_ROOT_PASSWORD=root_pass
    #image: 'bjornnborg/delayed-mysql:5.6'
    image: 'mysql:5.6'
    networks:
      - my-network

  rails-one:
    build:
      dockerfile: ./docker/app.dockerfile
      context: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    #command: bash ./rails-init.sh
    container_name: budget-on-sight-1
    networks:
      - my-network
    ports:
      - '3000:3000'
    depends_on:
      - mysql-service
