version: '3'
networks:
  my-network:
    driver: bridge

services:
  mysql-service:
    environment:
      - MYSQL_ROOT_PASSWORD=root_pass
    #image: 'bjornnborg/delayed-mysql:5.6'
    image: 'mysql:5.6'
    container_name: bos-mysql
    volumes:
      #- db_data:/var/lib/mysql
      - ./db_data:/var/lib/mysql
    networks:
      - my-network

  rails-one:
    build:
      dockerfile: ./docker/dev.dockerfile
      context: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/budget-on-sight
    #command: bash ./rails-init.sh
    container_name: bos-rails
    networks:
      - my-network
    ports:
      - '3000:3000'
    depends_on:
      - mysql-service

#volumes:
#  db_data:
